import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Roboto_Mono } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.css";
import "./globals.css";

// const inter = Inter({
//   subsets: ["latin"],
//   display: "swap",
// });

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto_mono.variable}`}>{children}</body>
    </html>
  );
}
